# Generated by Django 3.2.5 on 2021-10-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20211003_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_bank_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_number', models.CharField(max_length=20)),
                ('acc_name', models.CharField(max_length=30)),
                ('swift_code', models.CharField(max_length=20)),
            ],
        ),
    ]
