# Generated by Django 3.2.5 on 2021-10-19 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20211020_0136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_bank_details_user',
            name='profile_name',
        ),
        migrations.RemoveField(
            model_name='add_bank_details_user',
            name='profile_url',
        ),
    ]
